<?
/* @var $this Common\View */
$this->headTitle('Отзывы');
$this->inlineScript()->appendFile("/mobile/js/master-list.js");
$this->headLink()->appendStylesheet('/mobile/css/master-list.css');
?>

<a href="/" class="breadcrumb-bar">Главная</a>

<h1>Наши специалисты</h1>
<div class="master-list" data-url="<?= $this->url() ?>" data-page="1">
	<? echo $this->partial('/application/master/index.items.phtml', $this->vars()); ?>	
</div>
<nav class="pager">	
	<?= $this->sitePaginator($this->page, $this->pageCount, 'master-index'); ?>
</nav>

