<?
/* @var $this Common\View */
$item = $this->item;
$diplomas = $this->diplomas;
if(empty(trim($item['education'])) && empty($diplomas)){return ;}
?>

<section class="education purple">
	<h2>Образование</h2>
	<div class="content">
		<?= $item['education'] ?>
	</div>
	<? if(!empty($this->diplomas)){ ?>  
	<h2>Дипломы</h2>
	
	<ul class="diplomas">
	<? foreach ($diplomas as $diplom){ ?>
		<li><a href="<?= $diplom['image'] ?>" title="<?= $diplom['title'] ?>" data-fancybox="diplomas">
			<img src="<?= $this->image($diplom['image'], null, 266) ?>" /></a>
		</li>
	<? } ?>
	</ul>

	<? } ?>
</section>