<?
/* @var $this Common\View */
$album = $this->album;

$this->assets(['fancybox']);
$this->seo($album);
$this->headLink()->appendStylesheet("/mobile/css/video-index.css");

?>

<a  href="<?= $this->url('video-index') ?>" class="breadcrumb-bar">Все видео</a>

<h1>Видео: <?= $album ['title'] ?></h1>

<div class="videoalbum-wrp">
	<? 
	$i = 0;
	foreach ($this->videos as $video){ ?>
	<? if($i++ %5 == 0) echo '</div><div class="video-row">'; ?>
	<? echo $this->partial('application/video/index.item.phtml', ['item'=>$video]); ?>		
	<? } ?>
</div>
