<?
/* @var $this Common\View */
$this->headTitle("Видео");
$this->headLink()->appendStylesheet("/mobile/css/video-index.css");

?>

<a href="/"  class="breadcrumb-bar">Главная</a>

<? if(!empty($this->latest)){ ?> 
<div class="block">
	<h1 class="like-h2">Последние добавленные видео</h1>
	<? foreach ($this->latest as $video){ 
		echo $this->partial('application/video/index.item.phtml', ['item'=>$video]);
} ?>		
</div>
<? } ?>

<? if(!empty($this->top)){ ?>
<div class="block">
	<h2>Самое интересное</h2>
	<? foreach ($this->top as $video){ 
	echo $this->partial('application/video/index.item.phtml', ['item'=>$video]);
} ?>		
</div>
<? } ?>

<? foreach ($this->albums as $album){ ?>
<div class="block">
	<h2><? 
		$title = $album['title'];
		if(!empty($album['created'])) { 
			$title = '<span class="date">'.$this->html()->date($album['created'], 'M Y', '', '').'</span>'.$album['title'];
		};
		?>
		<a href="<?= $this->url('video-album', ['alias' => $album['alias']]) ?>"><?= $title ?> (<?= $album['video_count'] ?> видео)</a>
		
	</h2>
	
	<div class="photoalbum-wrp">
		<? foreach ($album['items'] as $item){ 
		echo $this->partial('application/video/index.item.phtml', ['item'=>$item, 'album' => $album]);
		} ?>
	</div>
</div>
<? } ?>