<?
/* @var $this Common\View */
$this->headLink()->appendStylesheet("/mobile/css/video.css");
$video = $this->video;
$album = $this->album;
$this->seo($video);
?>

<? if(!empty($album)){ ?>
<a href="<?= $this->url('video-album', ['alias' => $album['alias']]) ?>" class="breadcrumb-bar">Видео: <?= $album['title'] ?></a></li> 
<? } else { ?>
<a href="<?= $this->url('video-index') ?>" class="breadcrumb-bar">Все видео</a>
<? } ?>

<h1><?= $video['title'] ?></h1>

<div class="video-container">
	<?= $video['html_mobile'] ?>
</div>

<div class="content" data-editable="video-<?= $video['id'] ?>-body" >
<?= $video['body'] ?>
</div>

<?= $this->partial('/parts/after-article', ['item' => $video]); ?> 