<?php
use Admin\Model\Courses\EventDb;
use Admin\Model\Orders\OrdersDb;

/* @var $this Common\View */
	$type =  $this->type;
	$meetDate = $this->meet_date;
	$order = 	$this->order;
	$shedule = 	$this->shedule;
	$event = 	$this->event;
	$tarif = 	$this->tarif;
	$masters = 	$this->masters;
?>
<tr>
	<td class="-twm-popup-link" -href="#courseOrderPopup">		
		<? if($type == 'preorder'){ ?>
			<p><?= $event['date_text']?></p>
			<p class="secondary">Предварительная заявка</p>		
		<? } else { ?>
			<p><?= $this->html()->date($meetDate, 'd M') ?></p>
			<p><?= $this->html()->date($meetDate, 'l') ?></p>
		<? }?>
	</td>
	<td class="shedule-list--time" class="twm-popup-link" href="#courseOrderPopup">				
		<? if(!empty($event['time_text'])){ ?>
		<p class="time-till-wrp">		
			<? if(!empty($event['time_text_from'])){ ?>
			<span class="from"><?= $event['time_text_from'] ?></span>
			<? if(!empty($event['time_text_till'])){ ?>
			<span class="till"><?= $event['time_text_till'] ?></span>
			<? } ?>
			<? } else { ?> 
			<span class="from"><?= $event['time_text_duration'] ?></span>
			<? } ?>		
		</p>
		<? }?>	
	</td>
	<td class="-twm-popup-link" -href="#courseOrderPopup">		
		<p><?= $event['title'] ?></p>		
		<? if(!empty($masters)) {?>
		<p class="info">Ведущий: 
			<?= implode(', ', array_map(function($master){
			return '<a class="" href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
			}, $masters)); ?>
		</p>
		<? } ?>
			
		<? if($event['type'] != EventDb::TYPE_ANNOUNCE){ ?>
		<p class="info">Адрес: 
			<a href="javascrpt:;"><i class="icon-location"></i> м. Пушкинская, ул. Малая Дмитровка, 18а </a>			
		</p>
		<? } ?>
	</td>
	<td class="-twm-popup-link" -href="#courseOrderPopup"><?= $tarif['title'] ?></td>
	
	<td class="pay">			
		<? 
		if ($order['actual_price'] == 0){ ?>
			<label class="free">бесплатно</label>			
		<? } else if (empty($order['payed'])){ ?>
			<label class="checkbox">
				<input type="checkbox" name="payment" checked="checked" data-value="<? $order['actual_price'] ?>" />
				<span><?= number_format($order['actual_price'], 0, '.', ' ')?> р.</span>
				<? if($order['actual_price'] < $order['price'] && $order['price']!=0){ ?> 
				<span class="price-old"><?= number_format($order['price'], 0, '.', ' ')?> р.</span>
				<? } ?>
			</label>
		<? } else { ?>
			<label class="payed"><i class="icon-check-1"></i><?= number_format($order['payed'], 0, '.', ' ')?> р.</span></label>
		<? } ?>			
	</td>
	
	<td class="status">	
		<? if (empty($order['payed']) && ($order['status'] == OrdersDb::STATUS_PREORDER || $order['status'] == OrdersDb::STATUS_NEW) ){ ?>
			<a href="#removeCoursePopup" class="twm-popup-link">					
				<i class="icon-trash-empty"></i>
			</a>			
		<? } else { ?>
			<i class="icon-lock"></i>
		<? } ?>			
	</td>
</tr>	