<?
/* @var $this Common\View */
?>

<section class="services">
	<div class="lay-wrapper-inner">
		<h2 class="like-h1">Наш профиль</h2>
		<a class="block" href="<?= $this->url('content-division', ['alias' => 'otnosheniya-semya']) ?>">				
			<img src="/site/img/services-1.jpg" alt="Семья и отношения" />
			<span class="like-h2">Семья и отношения</span>
		</a>
		<a class="block" href="<?= $this->url('content-division', ['alias' => 'telo-emocionalnoe-sostoyanie-zdorove']) ?>">				
			<img src="/site/img/services-2.jpg" alt="Тело и здоровье" />
			<span class="like-h2">Тело и здоровье</span>				
		</a>
		<a class="block" href="<?= $this->url('content-division', ['alias' => 'rabota-biznes-karera']) ?>">				
			<img src="/site/img/services-3.jpg" alt="Бизнес и карьера" />
			<span class="like-h2">Бизнес и карьера</span>				
		</a>
		<div class="button-group">
			<a href="/shedule-list.php" class="button light">Расписание мероприятий</a>
			<a href="#signPopup" class="button purple twm-popup-link">Записаться на консультацию</a>
		</div>
	</div>
</section>