<?
use Common\ImageService;
/* @var $this Common\View */
$reviewItems = $this->review_items;
if (empty($reviewItems)){return ;}
?>

<section class="reviews purple clr-after">
	<h2 class="like-h1">Отзывы</h2>
	<div class="review-list after-clr">			
		<? 
		foreach ($reviewItems as $review){ 
		?>
		<div class="review-block">
			<img src="<?= $this->image($review['userpic'], ImageService::SIZE_REVIEW_USERPICK)?>" alt="<?= htmlentities($review['name']) ?>" />
			<span class="date"><i class="icon-calendar"></i><?= $this->html()->hdate($review['date']) ?></span>
			<? if($review['social']) { ?>
			<a href="<?= $review['social'] ?>" class="name" target="_blank">
				<? if(!empty($review['social_icon'])) { ?>
					<i class="icon-<?= $review['social_icon'] ?>"></i>
				<? } ?>
				<span><?= $review['name'] ?></span></a>
			<? } else {?>
			<span class="name"><?= $review['name'] ?></span>
			<?}?>				
			<div class="body purple">
				<?= $review['body'] ?>
			</div>
		</div>
		<? } ?>
	</div>
			
	<div class="button-group">
		<? if($this->review_totals['count'] > 2){?>
		<a href="<?= $this->url('review-index', ['p' => 1])?>" class="button light review-expander">Помотреть еще <?= $this->html()->grammar('отзыв',$this->review_totals['count'],'','а','ов', true) ?></a>
		<? } ?>
		<a href="#reviewPopup" class="button pink twm-popup-link">Оставить свой</a>
	</div>

</section>

<?= $this->popup('review'); ?> 
		


		