<?
/* @var $this Common\View */
?>
<div class="info-message white-bg">
	<div class="image">
		<img src="/site/img/thanks.jpg" alt="Спасибо!" title="Спасибо!"/>
	</div>
	<div>				
		<h2>Запись на мероприятие</h2> 
		<p>Вы записываетесь на мероприятие &laquo;<?= $this->shedule['event_title']?>&raquo;</p>		
		<? if(! empty($this->tarif)){ ?>
		<p>Тариф: <?= $this->tarif['title'] ?></p>
		<? } ?>		
		<p>Для успешного завершения <em>зарегестрируйтесь</em> на нашем сайте, или <em>войдите</em> под своими логином и паролем.</p>
	</div>	
</div>
