<?
/* @var $this Common\View */
/* @var $item array */
$shedule = $this->shedule;
if (!empty($shedule)) {;
?>
<h2>Расписание мероприятий на <?= $this->html()->date($this->calendar_date,'M Y', '', '') ?></h2>		
	<? foreach ($this->shedule as $date){ 
		echo $this->partial('application/courses/course-view.shedule.item.phtml', ['date' => $date]);			
	} ?>
		
	<nav class="month-pager">
	<?			
		$url = $this->url('course-shedule-part', ['id' => $this->item['id'], 'month' => 'dummy_date']);
		echo $this->monthPaginator($this->calendar_date, $this->shedule_bounds, 5, function($dt) use($url){
			return str_replace('dummy_date', date('y-m', $dt), $url);
		});				
	?>			
	</nav>
<? } ?>