<?
use Application\Controller\CoursesController;

/* @var $this Common\View */
/* @var $date array */
/* @var $tarif array */
$date = $this->date;
$event = $date['event']; 
?>
<div class="white-bg block">
	<div class="date-wrp">
		<p class="date-big"><?= $this->html()->date($date['date'], 'd')?></p>
		<p class="date"><?= $this->html()->date($date['date'], 'M')?></p>
		<p class="date"><?= $this->html()->date($date['date'], ' l')?></p>
	
		<? if(!empty($event['time_text'])){ ?>
		<p class="time-till-wrp">		
			<? if(!empty($event['time_text_from'])){ ?>
			<span class="from"><?= $event['time_text_from'] ?></span>
			<? if(!empty($event['time_text_till'])){ ?>
			<span class="till"><?= $event['time_text_till'] ?></span>
			<? } ?>
			<? } else { ?> 
			<span class="till"><?= $event['time_text_duration'] ?></span>
			<? } ?>		
		</p>
		<? }?>	
		<? /* if ($event['place']){ ?>
			<a class="location-link"><?= $dateArr[2] ?></a> 
		<?} */?>
	</div>
	<div class="text-wrp">
		<h3><?= $event['title'] ?></h3>
		<? if(!empty($date['masters'])){ ?>
		<p class="info">Ведущий: 
			<?= implode(', ', array_map(function($master){
			return '<a class="" href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
			}, $date['masters'])); ?>
		</p>	
		<? } ?>			
	</div>
	<div class="clr"></div>
	<table class="tarif-list">
	<tr><th colspan="3">Тарифы: </th>	
	<?
	foreach ($date['tarifs'] as $tarif) { ?>
		<tr>
		<td class="tarif-list--title"><?= $tarif['title'] ?></td>
		<td class="tarif-list--price">
			<? if($tarif['price'] == 0){ 
				echo '<span class="price free">бесплатно</span>';
			} else { ?>
			<span class="price-wrp">
				<? if($tarif['price'] != $tarif['actual_price']){ ?>
				<span class="price"><?= number_format($tarif['actual_price'], 0, '.', ' ')?> р.</span>
				<span class="price-old"><?= number_format($tarif['price'], 0, '.', ' ') ?></span>
				<? } else { ?>
				<span class="price"><?= number_format($tarif['actual_price'], 0, '.', ' ')?> р.</span>
				<? } ?>				
			<? } ?>
		</td>
		<td class="tarif-list--status">
			<? 
			if ($tarif['order_status'] == CoursesController::ORDER_STATUS_EXPIRED) {?>
				Запись окончена
			<? } else if ($tarif['order_status'] == CoursesController::ORDER_STATUS_AVAILABLE) {
					$getQuery = [
						'event' => $event['id'],
						'tarif' => $tarif['id'],
						'date' => $date['id']
					];			
				?>
				<a href="<?= $this->url('order-event',[], ['query' => $getQuery]) ?>">Записаться</a>
			<? } else if (
					$tarif['order_status'] == CoursesController::ORDER_STATUS_FREE || 
					$tarif['order_status'] == CoursesController::ORDER_STATUS_PAIED ) {?>
				<a class="signed" href="<?= $this->url('customer-calendar') ?>">Вы записаны</a>
			<? } else if ($tarif['order_status'] == CoursesController::ORDER_STATUS_NEED_PAY) {?>
				<span class="signed">Вы записаны</span>				
				<a href="<?= $this->url('customer-calendar') ?>">Оплатить</a>
			<? } ?>			
		</td>
	</tr>	
	<? } ?>
</table>
</div>
	
			
