<?
/* @var $this Common\View */
$item = $this->item;
if(!empty($item['author_alias']) && !empty($item['author_name']) && !empty($item['created'])){
	$cssClass = 'two-items';
} else {
	$cssClass = 'one-item';
} 
?>
<div class="after-article <?= $cssClass ?> clr-after">
	
	<? if(!empty($item['created'])){ ?>
	<span class="after-article-item">
		<i class="icon-calendar"></i><?= $this->html()->date($item['created'], 'd M Y') ?>
	</span>
	<? } ?>

	<? if(!empty($item['author_alias']) && !empty($item['author_name'])){ ?>
	<span class="after-article-item">	
		<label>Автор: </label><a href="<?= $this->url('master-view', ['alias' => $item['author_alias']]) ?>"><?= $item['author_name'] ?></a>
	</span>
	<? } ?>
	

	
  <script type="text/javascript">(function() {
	  if (window.pluso)if (typeof window.pluso.start == "function") return;
	  if (window.ifpluso==undefined) { window.ifpluso = 1;
    var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
    s.type = 'text/javascript'; s.charset='UTF-8'; s.async = true;
    s.src = ('https:' == window.location.protocol ? 'https' : 'http')  + '://share.pluso.ru/pluso-like.js';
    var h=d[g]('body')[0];
    h.appendChild(s);
  	}})();</script>
	<div class="pluso" data-background="transparent" data-options="medium,square,line,horizontal,counter,theme=01" data-services="vkontakte,odnoklassniki,facebook,twitter"></div>
	
</div>