<?
use Application\Controller\CatalogController;

/* @var $this Common\View */
?>

<div class="breadcrumb-bar">
	<a class="left" href="/">Главная</a>	
	<a class="right icon-search" href="javascript:;"></a>
</div>
<div class="purple-bg">
<form action="<?= $this->url('shedule', ['type' => $this->type]) ?>" class="form filter" id="sheduleFilterForm" method="get">
	<h2>Поиск по расписанию</h2>
	<div class="field">
		<label>Область тренинга</label>
		<select name="tag" class="gray">				
			<?= $this->html()->option('Все тренинги', '', $this->filter_tag['id'] ) ?>
			<? foreach ($this->filter_tag_options as $tagGroup){ ?>  
			<optgroup label="<?= $tagGroup['group_name'] ?>">	
				<? foreach ($tagGroup['items'] as $tag){ ?>  
				<?= $this->html()->option($tag['tag_name'], $tag['tag_id'], $this->filter_tag['id'] ) ?>						
				<? } ?>
			</optgroup>
			<? } ?>					
		</select>
	</div>
	
	<div class="field">
		<label>Специалист тренер</label>
		<select name="master" class="gray">
			<?= $this->html()->option('Все', '', $this->filter_master['id'] ) ?>
			<? foreach ($this->masterOptions as $master){ ?>  
			<?= $this->html()->option($master['name'], $master['id'], $this->filter_master['id'] ) ?>						
			<? } ?>
		</select>
	</div>
	
<? if (!empty($this->filter_tag2_options)){?>
	<div class="field">
		<label><?= $this->filter_tag2_options['group_name'] ?></label>
		<select name="tag2" class="gray">
			<?= $this->html()->option('Все', '', $this->filter_tag2['id'] ) ?>
			<? foreach ($this->filter_tag2_options['items'] as $tag){ ?>  
			<?= $this->html()->option($tag['tag_name'], $tag['tag_id'], $this->filter_tag2['id'] ) ?>						
			<? } ?>
		</select>
	</div>
<? } ?>

	<div class="field">
		<label>Область тренинга</label>
		<select name="tag" class="gray">				
			<?= $this->html()->option('Все тренинги', '', $this->filter_tag['id'] ) ?>
			<? foreach ($this->filter_tag_options as $tagGroup){ ?>  
			<optgroup label="<?= $tagGroup['group_name'] ?>">	
				<? foreach ($tagGroup['items'] as $tag){ ?>  
				<?= $this->html()->option($tag['tag_name'], $tag['tag_id'], $this->filter_tag['id'] ) ?>						
				<? } ?>
			</optgroup>
			<? } ?>					
		</select>
	</div>

	<div class="button-group">
				
		<a href="<?= $this->url('catalog-index', ['type' => CatalogController::TYPE_ANNOUNCEMENTS], [], true) ?>" class="button white">Анонсы</a>
		<button type="submit" class="button pink">Поиск</button>
		
	</div>

</form>
</div>