<?
use Application\Controller\CoursesController;

/* @var $this Common\View */
$course = $this->course;

$dates = $this->dates;

?>

<div class="block white-bg column-view-item" data-href="<?= $this->url('course-view', ['alias' => $course['alias']]) ?>" style="background-image: url(<?= $this->image($course['image'], 420, 195) ?>)">
	<h2 class="like-h3"><?= $course['title'] ?></h2>		
		<? if(!empty($course['tags'])) {?>
			<p class="info">
				<? foreach ($course['tags'] as $tag) {?>
				<a href="<?= $this->url('catalog-index', ['tag' => $tag['alias']]) ?>"><i class="icon-tag"></i><?= $tag['name'] ?></a>	
				<? } ?>
			</p>
		<? }?>	
		
		<? if(!empty($course['masters'])) {?>
			<p class="info">
				<label>Ведущий: </label>				
				<?= 
				
				implode(', ', array_map(function($master){
					return '<a href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
				}, $course['masters'])); 
				
				?>
			</p>
		<? }?>
		
		<? if(!empty($course['summary'])){ ?>
		<div class="summary">		
			<?= $this->html()->plain2html( $course['summary']) ?>
		</div>					
		<? } ?>
		
		<? if(!empty($dates)) {?>
		<h4>Расписание на <?= $this->monthDesc ?></h4>			
		<? foreach ($dates as $date){ 
			$dateDesc = $this->html()->date($date['date'], 'd l');
			$timeDesc = $date['event']['time_text_from'] ? : date('H:i', $date['date']);
			?>		
			<? if($date['order_status'] == CoursesController::ORDER_STATUS_EXPIRED){ ?>
			<span class="dates expired">
				<span class="to-left"><?= $dateDesc ?></span>
				<span class="to-right"><?= $timeDesc ?></span>				
			</span>	
			<? } else if($date['order_status'] == CoursesController::ORDER_STATUS_AVAILABLE){ 
			$query = [
				'date' => $date['id'],
			]?>
			<a href="<?= $this->url('order-event-popup', [], ['query' => $query]) ?>" class="dates twm-popup-link">
				<span class="to-left"><?= $dateDesc ?> </span>
				<span class="to-right">записаться</span>
				<span class="time"><?= $timeDesc ?></span>				
			</a>		
			<? } else { ?>		
			<a href="<?= $this->url('customer-calendar') ?>" class="dates">
				<span class="to-left"><?= $dateDesc ?></span>
				<span class="to-right checked-in">вы записаны</span>
				<span class="time"><?= $timeDesc ?></span>				
			</a>
		<? } ?>
		<? } ?>
		<? } ?>
</div><?