<?
/* @var $this Common\View */
$this->headTitle('Расписание');

$this->inlineScript()->appendFile('/mobile/js/course-order-popup.js');

$this->inlineScript()->appendFile('/mobile/js/shedule.js');
$this->headLink()->appendStylesheet('/mobile/css/_course-order.css');
$this->headLink()->appendStylesheet('/mobile/css/shedule.css');

echo $this->partial('application/shedule/filter.phtml', $this->vars());
?>

<h1>Расписание мероприятий</h1>

<select class="week-select-pager" class="gray">
	<? 
	$url = $this->url(null, ['date' => 'dummy_date'], [], true);
	echo $this->weekPaginatorOptions($this->currentDate, $this->sheduleBounds, 6, function($dt) use($url){
		return str_replace('dummy_date', date('y-m-d', $dt), $url);
	}); ?>
</select>
<?
if(!empty($this->items)){ ?> 
<div class="shedule-list">	
<?
  foreach ($this->items as $date => $dateItems){ 	
	foreach ($dateItems as $key => $item){
	  echo $this->partial('shedule-list.item.phtml', ['item' => $item, 'date' => $date]);
	}
	echo '<br /><br />';
  }
?>
</div>

<select class="week-select-pager" class="gray">
	<? 
	$url = $this->url(null, ['date' => 'dummy_date'], [], true);
	echo $this->weekPaginatorOptions($this->currentDate, $this->sheduleBounds, 6, function($dt) use($url){
		return str_replace('dummy_date', date('y-m-d', $dt), $url);
	}); ?>
</select>

<? } else { ?>
	<p class="empty-list-message">Мероприятия на этой неделе не запланированы</p>
<? } ?>