<?
use Common\Utils;

/* @var $this Common\View */
$this->headTitle("Мероприятие");
$this->assets(['autocomplete']);
$this->sidebar()->left('admin/courses/event/event-index.filter.phtml', $this->vars());
?>
<ul class="breadcrumb">
	<li><a href="<?= $this->url('private') ?>">Главная</a></li>	
</ul>
<h1 class="page-header">Расписание мероприятий / <?= $this->html()->date($this->page_bounds['from'], 'M Y', '', '') ?> 
	<small>всего: <?= $this->calendar_bounds['count'] ?></small></h1>

<table class="item-list" data-deletion-confirm="Вы уверены, что хотите удалить этот объект?">
	<thead>
		<tr>
			<th style="width: 60px" class="tc">№</th>
			<th class="tc" style="width: 120px">Дата</th>
			<th class="tl" style="width: 60px">Время</th>
			<th>Курс / Мероприятие</th>
			<th>Периодичность</th>			
			<th>Заказов</th>
			<th></th>
		</tr>
	</thead>
	<?
	foreach ($this->calendar_items as $cItem) {
		$date = strtotime($cItem['formated_date']);
		$count = count($cItem['items']);
		$w = date('w', $date);
		if($w == 0 || $w == 6){
			$dateClass = ' holiday';
		} else {
			$dateClass = '';
		}
		foreach ($cItem['items'] as $i => $item) {
		?>
		
	<tr data-href="<?=$this->url('private/event-edit', ['id' => $item['id']])?>">
		<td class="tc" ><?= $item['id']?></td>
		<? if($i == 0){ ?>
		<td class="tl date-column" style="width: 40px" rowspan="<?= $count ?>">		
			<span class="date<?= $dateClass ?>"><?= $this->html()->date($date,'d') ?></span>
			<span class="week-day<?= $dateClass ?>"><?= $this->html()->date($date,'l') ?></span>
		</td>
		<? } ?>
		<td class="tl" style="width: 70px"><?= $this->html()->date($item['date'],'H:i') ?></td>		
		<td>
			<a href="<?= $this->url('private/course-edit', ['id' => $item['course_id']]) ?>" title="Курс: <?= htmlentities($item['course_title'])?>">
				<?= Utils::substrByWord($item['course_title'], 100)  ?></a>
				<? if($item['course_title'] != $item['title']){  
					echo ' / '.Utils::substrByWord($item['title'], 100);
				} ?>				
			</td>
		<td><?= $item['type_name'] ?></td>		
		<td><?
		if(!empty($item['order_count'])){
			echo $item['order_count'];
		} ?></td>
		<td class="options">
			 <a href="<?= $this->url('private/event-status', ['id' => $item['id']]) ?>" class="item-status">
				<i class="fa fa-check <?= $item['status'] ? 'active': '' ?>"></i></a>
				<a href="<?= $this->url('private/event-delete', ['id' => $item['id']]) ?>" class="fa fa-trash item-delete"></a>			
		</td>
	</tr>
		<? } ?>
	<?}?>
</table>
<div class="pagination">
<?
$url = $this->url(null, ['p' => 'dummy_date']);
echo $this->monthPaginator($this->page_bounds['from'], $this->calendar_bounds, 15, function($dt) use($url){
			return str_replace('dummy_date', date('y-m', $dt), $url);
		});
?>
</div>