<?
/* @var $this Common\View */
/* @var array $photo */
$size = $this->image()->getSize($this->photo['image']);
if(empty($this->album)){
	$url = $this->url('photo-latest');
} else {
	$url =$this->url('photo-album', ['alias' => $this->album['alias']]);
}
	?>
<a href="<?= $url ?>" class="item">
	<img src="<?= $this->image($this->photo['image'], 100, 75) ?>" alt="<?= $this->photo['title'] ?>"/>
</a>