<?
/* @var $this Common\View */

$this->inlineScript()->appendFile('/assets/fancybox/jquery.fancybox.min.js');
$this->headLink()->appendStylesheet("/assets/fancybox/jquery.fancybox.min.css");

$this->headLink()->appendStylesheet("/mobile/css/photo.css");

?>

<a href="<?= $this->url('photo-index') ?>" class="breadcrumb-bar" >Все фотоальбомы</a>

<h1>Последние добавленные фото</h1>

<div class="photoalbum-wrp">
	<? foreach ($this->photos as $photo){ ?>
	<? echo $this->partial('application/photo/album.item.phtml', ['photo'=>$photo]); ?>		
	<? } ?>
</div>

<?= $this->content('photo-latest', true); ?>