<?
/* @var $this Common\View */
?>

<div class="image-wrp">
	<img src="<?= $this->image($item['image'], 135, 135) ?>" alt="<?= $item['name'] ?>" />
</div>
<div class="search-description" data-href="<?= $this->url('master-view', ['alias' => $item['alias']])?>">
	<h2 class="like-h3">Специалист: <?= $item['name'] ?></h2>		
	<? if(!empty($item['summary'])){ ?>
	<div class="summary">		
		<?= $this->html()->plain2html( $item['summary']) ?>
	</div>					
	<? } ?>		
	
	<? if(!empty($item['courses'])) {?>
	<p class="info">
	<label>Курсы: </label>
		<?
		echo implode(', ', array_map(function ($course) {
			return '<a href="'.$this->url('course-view', ['alias' => $course['alias']]).'">' . $course['title'] . '</a>';
		}, $item['courses']));
		?>
	</p>
	<? }  ?>
</div>