<?
/* @var $this Common\View */

 ?>

<div class="info-message white-bg">
	<div class="image">
		<img src="/site/img/thanks-email.jpg" alt="Спасибо!" title="Спасибо!"/>
	</div>
	<div>				
		<h2>Вы успешно зарегестривались в системе</h2> 
		<p>На Ваш электронный адрес выслано письмо со ссылкой.</p>
		<p>Для подтверждения email следуйте инструкциям в этом письме.</p>
		<p><a href="#">выслать письмо еще раз</a></p>
	</div>	
</div>

