<?
/* @var $this Common\View */
$shedule = 	$this->shedule;
$isAnnounce = empty($shedule);
$event = 	$this->event;
$tarif = 	$this->tarif;
$masters =  $this->masters;
 ?>

<div class="info-message white-bg">
	<div class="image">
		<img src="/site/img/thanks.jpg" alt="Спасибо!" title="Спасибо!"/>
	</div>
	<div>	
		<h2>Спасибо</h2>
		<? if($isAnnounce){ ?>
		<p>Ваша заявка на участие в &laquo;<?= $event['title'] ?>&raquo; принята</p>
		<? } else { ?>
		<p>Вы только что зарегестрировались на курс &laquo;<?= $event['title'] ?>&raquo;</p>
		<? } ?>
		
		<? if(!empty($tarif)){ ?> 
		<p>Тариф - <?= $tarif['title'] ?>, 
			<? if($tarif['price'] == 0){ ?>
			<span class="free">бесплатно</span>
			<? } else if($tarif['price'] != $tarif['actual_price']){ ?>
			<span class="price"><?= number_format($tarif['actual_price'], 0, '.', ' ')?> р.</span>
			<span class="price-old" ><?= number_format($tarif['price'], 0, '.', ' ')?></span>
			<? } else { ?>			
			<span class="price"><?= number_format($tarif['actual_price'], 0, '.', ' ')?> р.</span>
			<? } ?>			
		</p>
		<? } ?>
		
		<? if(!empty($masters)){ ?> 
		<p>Ведущий: 
			<?= implode(', ', array_map(function($master){
					return '<a href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
				}, $masters)); ?></p>
		<? } ?>	 
		
		
		<p>	
			<? if($isAnnounce){ ?>
			<i class="icon-calendar"></i><?= $event['date_text'] ?>
			<? } else { ?>
			<i class="icon-calendar"></i><?= $this->html()->date($shedule['date'], 'd M, l') ?>
			<? }			
			if(!empty($event['time_text'])){ ?>			
			&nbsp;&nbsp;&nbsp;&nbsp;
			<i class="icon-clock"></i> 
				<? if(!empty($event['time_text_from'])){ ?>
				c <?= $event['time_text_from'] ?>
				<? if(!empty($event['time_text_till'])){ ?>
				до <?= $event['time_text_till'] ?>
				<? } ?>
				<? } else { ?> 
				<?= $event['time_text_duration'] ?>
				<? } ?>
			<? } ?>			
		</p>
		<? if(!$isAnnounce){ ?>	
		<p>
			<a href="javascrpt:;"><i class="icon-location""></i> м. Пушкинская, ул. Малая Дмитровка, 18а </a>
		</p>
		<? } else { ?>		
		<p class="sign">Наш менеджер свяжется с Вами и уточнит время и место мероприятия</p>
		<? } ?>
	</div>
</div>