<?= '<?' ?>

<?
/* @var $entity Entity */ ?>
namespace <?= $entity->getControllerNamespace() ?>;

use <?= $entity->getFormClassFull() ?>;
use <?= $entity->getDbClassFull() ?>;
use Common\Annotations\Layout;
use Common\Annotations\Roles;
use Common\CRUDController;
use Common\CRUDEditModel;
use Common\ViewHelper\Flash;
use ZfAnnotation\Annotation\Controller;
use ZfAnnotation\Annotation\Route;
use Zend\View\Model\JsonModel;

/**
 * @Controller
 * @Roles(value="admin")
 * @Layout(value="private")
 * @property <?= $entity->getDbClass() ?> $db 
 */
class <?= $entity->name ?>Controller extends CRUDController implements CRUDEditModel{
	
	/** @var <?= $entity->getDbClass() ?> */
	var $db;
	
	public function init(){
		$this->db = $this->serv(<?= $entity->getDbClass() ?>::class);		 
		$this->crudInit();
	}
	
	/**
	 * @Route(name="<?= $entity->route ?>-index",route="/<?= $entity->route ?>-index[/f-:f][/p-:p]",extends="private",type="segment")
	 */
	public function <?= lcfirst($entity->name) ?>IndexAction(){		
		return $this->crudList($this->db);		
	}
	
	protected function index(){
				
	}
	
	/**
	 * @Route(name="<?= $entity->route ?>-edit", route="/<?= $entity->route ?>-edit/:id",extends="private",type="segment")
	 */
	public function <?= lcfirst($entity->name) ?>EditAction(){
		return parent::processEditForm(<?= $entity->getFormClass() ?>::class, $this);
	}
		

	/* CRUD Model *************************** */
	
	public function load($id) {
		$item = $this->db->get($id);
		return $item;
	}

	public function create() {
		// return [];
	}

	public function validate(array $data){
		
	}
	
	public function save(array $data){
		
		if($this->isNew){						
			$this->id = $this->db->insert($data);			
			if($this->id == null) throw new \Exception("<?= $entity->message('error_insert') ?>");
		} else {
			$this->db->updateOne($data, $this->id);			
		}		
		return $this->id;
	}
	
	public function afterSave(){
		if($this->isNew){
			$this->sendFlashMessage("<?= $entity->message('success_insert') ?>", Flash::SUCCESS);
		} else {
			$this->sendFlashMessage("<?= $entity->message('success_save') ?>", Flash::SUCCESS);
		}
		
		return $this->afterSaveRedirect();
	}
	
	public function edit(){
		<? if(!empty($entity->clientRoute)) { 
		?>if($this->id){
			$this->layout()->site_url = $this->url()->fromRoute('<?= $entity->route ?>', ['id' => $this->id]);
		}
		<? } else if(isset($entity->fields['alias'])) {
		?>if(!$this->isNew){
			// $this->layout()->site_url = $this->url()->fromRoute('<?= $entity->route ?>', ['alias' => $this->item['alias']]);
		}
		<? } else { 
		?>if(!$this->isNew){
			// $this->layout()->site_url = $this->url()->fromRoute('<?= $entity->route ?>', ['id' => $this->id]);
		}
		<? } 
		?>return [
			'stat' => $this->db->getStat($this->item['id'])
		];
	}
	
	
	/**
     * @Route(name="<?= $entity->route ?>-delete", route="/<?= $entity->route ?>-delete/:id",extends="private",type="segment")
     */
    public function deleteAction(){
    	$id = $this->params('id', 'new');

    	$this->db->deleteOne($id);
    	return new JsonModel(['result' => 'ok']);
//     	return new JsonModel(['result' => 'error', 'message' => 'Удаление невозможно.']);
    }
    
    
    <? if(isset($entity->fields['status'])){
    ?>    	
    /**
     * @Route(name="<?= $entity->route ?>-status", route="/<?= $entity->route ?>-status/:id",extends="private",type="segment")
     */
    public function statusAction(){
    	$id = $this->params('id', 'new');
    	$item = $this->db->get($id);
    	if(empty($item)){
    		return new JsonModel(['result' => 'error', 'message' => 'Объект не найден']);
    	}
    	$update = ['status' => 0];
    	if($item['status'] == 0){
    		$update['status'] = 1;
    	}
    	$this->db->updateOne($update, $id);
    	return new JsonModel(['result' => 'ok', 'status' => $update['status']]);    	 
    }
    <? }
    ?>
	
}

