<?
/* @var $this Common\View */
$this->headTitle('Расписание');
$this->inlineScript()->appendFile('/site/js/shedule.js');

$this->inlineScript()->appendFile('/site/js/course-order-popup.js');
$this->headLink()->appendStylesheet('/site/css/_course-order.css');

$this->headLink()->appendStylesheet('/site/css/shedule.css');
echo $this->partial('application/shedule/filter.phtml', $this->vars());

?>
<nav class="month-pager">
	<? $url = $this->url(null, ['date' => 'dummy_date'], [], true);
echo $this->monthPaginator($this->currentDate, $this->sheduleBounds, 4, function($dt) use($url){
	return str_replace('dummy_date', date('y-m-01', $dt), $url);
}); ?>
</nav>	
<? if(!empty($this->items)){ ?> 
<div class="shedule-blocks column-view">
	<div class="column column-1"></div>
	<div class="column column-2"></div>
	<div class="column column-3"></div>
	
	<? foreach ($this->courses as $course){ 
	
		echo $this->partial('application/shedule/shedule-blocks.item.phtml', [
				'dates' => $this->items[$course['id']], 
				'course' => $course,
				'monthDesc' => $this->html()->date($this->currentDate, 'M Y', '', '')
			]); 
	
	} ?>
					
</div>
<nav class="month-pager">
	<? $url = $this->url(null, ['date' => 'dummy_date'], [], true);
echo $this->monthPaginator($this->currentDate, $this->sheduleBounds, 4, function($dt) use($url){
	return str_replace('dummy_date', date('y-m-01', $dt), $url);
}); ?>
</nav>	
<? }  else { ?>
	<p class="empty-list-message">Мероприятия в этом месяце не запланированы</p>
<? } ?>