<?
use Common\ImageService;

/* @var $this Common\View */
$this->headTitle("Баннеры");
$this->assets(['fancybox']);
$this->sidebar()->left('admin/content/banner/banner-index.filter.phtml', $this->vars());
?>
<ul class="breadcrumb">
	<li><a href="<?= $this->url('private') ?>">Главная</a></li>	
</ul>
<h1 class="page-header">Баннеры на главной <small><?= $this->counts['count'] ?></small></h1>

<table class="item-list" data-deletion-confirm="Вы уверены, что хотите удалить этот объект?">
	<thead>
		<tr>
			<th style="width: 60px" class="tc"><?= $this->sorter('№', 'id', $this->filter['sort']) ?></th>
			<th style="width: 60px" ></th>
			<th><?= $this->sorter('Внутреннее название', 'alias', $this->filter['sort']) ?></th>
			<th><?= $this->sorter('Показывать с', 'date_from', $this->filter['sort']) ?></th>
			<th><?= $this->sorter('Показывать до', 'date_to', $this->filter['sort']) ?></th>
			<th><?= $this->sorter('Ссылка', 'link', $this->filter['sort']) ?></th>			
			<th class="tc"><?= $this->sorter('Приоритет', 'priority', $this->filter['sort']) ?></th>
			<th></th>
		</tr>
	</thead>
	<?foreach ($this->items as $item) {?>
	<tr data-href="<?=$this->url('private/banner-edit', ['id' => $item['id']])?>">
		<td class="tc"><?= $item['id']?></td>
		<td class="image">
			<a href="<?= $this->image( $item['image']) ?>" data-fancybox="gallery" title="<?= htmlspecialchars($item['alias']) ?>">
				<img src="<?= $this->image( $item['image'], ImageService::SIZE_ADMIN_LIST_THUMB ) ?>" />
			</a>
		</td>
		<td><?= $item['alias'] ?></td>
		<td><?= $this->html()->date($item['date_from'], 'd.m.Y h:i') ?></td> 
		<td><?= $this->html()->date($item['date_to'], 'd.m.Y h:i') ?></td>
		<td><?= $item['link'] ?></td>
		<td class="tc"><?= $item['priority'] ?></td>		
		<td class="options">
			 <a href="<?= $this->url('private/banner-status', ['id' => $item['id']]) ?>" class="item-status">
				<i class="fa fa-check <?= $item['status'] ? 'active': '' ?>"></i></a>
				
			<a href="<?= $this->url('private/banner-delete', ['id' => $item['id']]) ?>" class="fa fa-trash item-delete"></a>			
		</td>
	</tr>
	<?}?>
</table>	

<?= $this->html()->pages($this->page, $this->pageCount) ?>
