<?
/* @var $this Common\View */
$this->headTitle('Отзывы');
$this->inlineScript()->appendFile("/site/js/reviews.js");
$this->headLink()->appendStylesheet('/site/css/reviews.css');
?>
<ul class="breadcrumb">
	<li><a href="/">Главная</a></li>
	<? if(empty($this->subject)){ ?>
	<li>Все отзывы</li>
	<? } else {?>
	<li><a href="<?= $this->url(null)?>">Все отзывы</a></li>
	<li><?= $this->title ?></li>
	<? } ?>	
</ul>

<h1><?= $this->title ?></h1>

<? if(!empty($this->items)) { ?>
<div class="review-list after-clr column-view" data-url="<?= $this->url(null, ['subject' => $this->subject])?>" data-page="1">
	<div class="column column-1"></div>
	<div class="column column-2"></div>
	<? echo $this->partial('/application/reviews/index.items.phtml', $this->vars()); ?>	
</div>
<p class="ajax-list-loading">Загрузка...</p>
<? } else { ?>
<div class="review-list" style="margin: 0 auto; width: 482px;">
<? echo $this->partial('/application/reviews/index.form.phtml', $this->vars()); ?>
</div>
<? } ?>