<?
use Common\ImageService;
use Admin\Model\Content\ReviewRefsDb;
/* @var $this Common\View */

	$refsTexts = [];
	if(count($review['refs']) > 0){
		foreach ($review['refs'] as $ref){				
			if($ref['entity'] == ReviewRefsDb::ENTITY_MASTER){ 
				$refsTexts[] = 'специалисте <a href="'. $this->url('master-view', ['alias' => $ref['item_alias']]) .'">'. $ref['item_displayname'] .'</a>';
			} else {
				$refsTexts[] = 'курсе <span>'. $ref['item_title'] .'</span>';
			}					
		}
	}
	?>
	<div class="review-block column-view-item">
		<img src="<?= $this->image($review['userpic'], ImageService::SIZE_REVIEW_USERPICK)?>" alt="<?= htmlentities($review['name']) ?>" />
		<span class="date"><i class="icon-calendar"></i><?= $this->html()->hdate($review['date']) ?></span>
		<? if($review['social']) { ?>
			<a href="<?= $review['social'] ?>" class="name" target="_blank">
			<? if(!empty($review['social_icon'])) { ?>
				<i class="icon-<?= $review['social_icon'] ?>"></i>
			<? } ?>
			<span><?= $review['name'] ?></span></a>
		<? } else {?>
		<span class="name"><?= $review['name'] ?></span>
		<?}?>				
		<div class="body white">
			<? if(!empty($refsTexts)) { ?>
				<p class="review-subject">Отзыв о <?= implode(', ',$refsTexts)?></p>
			<? } ?>
			<div data-editable="review-<?= $review['id'] ?>-body" >
			<?= $review['body'] ?>
			</div>
		</div>
	</div>	
