<?
/* @var $this Common\View */
$this->headTitle('Отзывы');
$this->inlineScript()->appendFile("/mobile/js/reviews.js");
$this->headLink()->appendStylesheet('/mobile/css/reviews.css');
?>

<? if(empty($this->subject)){ ?>
	<a href="/" class="breadcrumb-bar">Главная</a>
	<? } else {?>
	<a href="<?= $this->url(null)?>" class="breadcrumb-bar">Все отзывы</a>
	<? } ?>

<h1><?= $this->title ?></h1>

<div class="review-list">
<? echo $this->partial('/application/reviews/index.form.phtml', $this->vars()); ?>
<? foreach ($this->items as $key => $review){ ?>		
	<? echo $this->partial('/application/reviews/index.item.phtml', ['review' => $review]); ?>
<? } ?>		
</div>
<nav class="pager">	
	<?= $this->sitePaginator($this->page, $this->pageCount, 'review-index'); ?>
</nav>
