<?php
use Common\ViewHelper\Phone;
/* @var $this Common\View */

?>
<div class="twm-popup" id="callMePopup" >	
	<form action="<?= $this->url('order-call') ?>" method="post" class="form">
		<h3>Позвоните мне</h3>		
		<p>Заполните форму и наш менеджер свяжется с Вами в ближайшее время</p>
		<p class="error-msg">Заполните все поля</p>
		<div class="field">
			<label class="reqired">Телефон для связи с Вами</label>
			<input type="text" name="phone" class="text-input" value="<?= Phone::format($this->identity()->phone) ?>" style="font-family: Consolas,Monaco,Lucida Console,monospace"/>
		</div>
		<div class="field">
			<label>Ваше имя</label>
			<input type="text" name="name" value="<?= $this->identity()->displayname ?>"/>
		</div>
		<div class="field">
			<label>Ваш вопрос</label>
			<textarea name="message" ></textarea>
		</div>
		<div class="buttons">		
			<input type="submit" class="button purple" value="Отправить"/>
		</div>		
	</form>
	<div class="done">		
		<h2>Cообщение отправлено</h2>
		<p>Вскоре наши операторы свяжутся с Вами</p>
		<div class="buttons">
			<a href="javascript:;" class="button purple twm-close" >OK</a>
		</div>
	</div>
</div>
