<?
/* @var $this Common\View */
$this->headTitle("Теги");

$this->sidebar()->left('admin/content/tag/tag-index.filter.phtml', $this->vars());
?>
<ul class="breadcrumb">
	<li><a href="<?= $this->url('private') ?>">Главная</a></li>	
</ul>
<h1 class="page-header">Теги <small><?= $this->counts['count'] ?></small></h1>

<table class="item-list" data-deletion-confirm="Вы уверены, что хотите удалить этот объект?">
	<thead>
		<tr>
			<th style="width: 60px" class="tc">№</th>
			<th>Группа</th>
			<th>Название</th>
			<th>УРЛ</th>
			<th title="Кол-во связанных курсов" class="tc">Курсы</th>
			<th title="Кол-во связанных статей" class="tc">Статьи</th>
			<th title="Используется в фильтре курсов" class="filter-td">Фильтр</th>
			<th></th>
		</tr>
	</thead>
	<?foreach ($this->items as $item) {?>
	<tr data-href="<?=$this->url('private/tag-edit', ['id' => $item['id']])?>">
		<td class="tc"><?= $item['id']?></td>
		<td><?= $item['group_name'] ?></th>
		<td><?= $item['name'] ?></th>
		<td><?= $item['alias'] ?></th>
		<td class="tc"><?= $item['ref_count_course'] ?></th>
		<td class="tc"><?= $item['ref_count_content'] ?></th>
		<td class="filter-td">
			<a href="<?= $this->url('private/tag-status', ['field' => 'filter', 'id' => $item['id']]) ?>" class="item-status">
				<i class="fa fa-filter <?= $item['filter'] ? 'active': '' ?>"></i></a>
		</td>
		<td class="options">
			<a href="<?= $this->url('private/tag-status', ['id' => $item['id']]) ?>" class="item-status">
				<i class="fa fa-check <?= $item['status'] ? 'active': '' ?>"></i></a>
			<a href="<?= $this->url('private/tag-delete', ['id' => $item['id']]) ?>" class="fa fa-trash item-delete"></a>			
		</td>
	</tr>
	<?}?>
</table>	

<?= $this->html()->pages($this->page, $this->pageCount)?>
