<?
/* @var $this Common\View */
$item = $this->item;

?><div class="block" data-href="<?= $this->url('course-view', ['alias' => $item['alias']]) ?>">
	<img src="<?= $this->image($item['image'], 420, 195) ?>" alt="<?= $item['title'] ?>" />
	<h2 class="like-h3"><?= $item['title'] ?></h2>		
	<? if(!empty($item['tags'])) {?>
			<p class="info">
				<? foreach ($item['tags'] as $tag) {?>
				<a href="<?= $this->url('catalog-index', ['tag' => $tag['alias']]) ?>"><i class="icon-tag"></i><?= $tag['name'] ?></a>	
				<? } ?>
			</p>
	<? }?>		
	<? if(!empty($item['masters'])) {?>
		<p class="info">
		<label>Тренер: </label>
		
			<?= implode(', ', array_map(function($master){
					return '<a href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
				}, $item['masters'])); ?>
		 
		</p>
	<? } ?>		
	<? if(!empty($item['summary'])){ ?>
	<div class="summary">		
		<?= $this->html()->plain2html( $item['summary']) ?>
	</div>					
	<? } ?>		
	
	<? if(!empty($item['dates'])) {?>
	<p class="info">
	<label>Запись на мероприятие: </label>
		<?
		echo implode(', ', array_map(function ($dateItem) use ($item) {
			return '<a href="'.$this->url('course-view', ['alias' => $item['alias']]).'">' . $this->html()->hdate($dateItem['date']) . '</a>';
		}, $item['dates']));
		?>
	</p>
	<? } else if(!empty($item['announcements'])) {
		$annons = $item['announcements'][0];
		$query = [
			'event' => $annons['id']
		];
		?>
	<p class="info">
		<label>Открыта предварительная запись</label> <a href="<?= $this->url('course-view', ['alias' => $item['alias']]) ?>" class="like" ><?= $annons['date_text'] ?></a>
	</p>
	<? } else { ?>
	<p class="info">
		<label>Запись окончена</label> <a href="#" class="like">Следить за расписанием <i class="icon-heart"></i></a>
	</p>
	<? }?>
</div>
