<?

return [ 
		'history_db_settings' => [ 
				'content' => [
						'type'       => 'Тип:  %2$s → %1$s',
						'title_ru'   => 'Заголовок (Ру): %2$s → %1$s',
						'title_en'   => 'Заголовок (En): %2$s → %1$s',						
						'status'     => 'Статус: %2$s → %1$s',
						'priority'     => 'Порядок: %2$s → %1$s',
						'filter'     => 'В фильтре: %2$s → %1$s',
						'body_ru'    => 'Изменен тект (Ру)',
						'body_en'    => 'Изменен тект (En)',						
						'alias' 	 => 'Урл: %2$s → %1$s',
						'author'	 => 'Автор: %2$s → %1$s',
						'created' 	 => 'Дата: %2$s → %1$s',
						'seo_title_ru'  => 'SEO title (Ру): %2$s → %1$s',  
						'seo_title_en'  => 'SEO title (En): %2$s → %1$s',  
						'seo_description_ru' => 'SEO description (Ру): %2$s → %1$s',  
						'seo_description_en' => 'SEO description (En): %2$s → %1$s',  
						'seo_keywords_ru' 	 => 'SEO keywords (Ру): %2$s → %1$s',  
						'seo_keywords_en'	 => 'SEO keywords (En): %2$s → %1$s',
						'add_tag' => 'Добавлен тег %1$s',
						'remove_tag' => 'Удален тег %2$s',
						'add_course' => 'Добавлен курс %1$s',
						'remove_course' => 'Удален курс %2$s',
						'_create' => 'Статья создана',
						'_delete' => 'Статья удалена',
				],
				'content_division' => [
						'title_ru'   => 'Заголовок (Ру): %2$s → %1$s',
						'title_en'   => 'Заголовок (En): %2$s → %1$s',
						'status'     => 'Статус: %2$s → %1$s',
						'priority'     => 'Порядок: %2$s → %1$s',
						'alias' 	 => 'Урл: %2$s → %1$s',
						'image' 	 => 'Изображение: %2$s → %1$s',
						'seo_title_ru'  => 'SEO title (Ру): %2$s → %1$s',
						'seo_title_en'  => 'SEO title (En): %2$s → %1$s',
						'seo_description_ru' => 'SEO description (Ру): %2$s → %1$s',
						'seo_description_en' => 'SEO description (En): %2$s → %1$s',
						'seo_keywords_ru' 	 => 'SEO keywords (Ру): %2$s → %1$s',
						'seo_keywords_en'	 => 'SEO keywords (En): %2$s → %1$s',
						'_create' => 'Раздел создан',
						'_delete' => 'Раздел удален',
				], 
				'user' => [
						'displayname' => 'Имя пользователя: %2$s → %1$s',
						'email'  => 'Электронная почта: %2$s → %1$s',
						'phone'  => 'Телефон: %2$s → %1$s',
						'skype'  => 'Skype: %2$s → %1$s',
						'vk_id'  => 'VK: %2$s → %1$s',
						'fb_id'  => 'FB: %2$s → %1$s',
						'password'  => 'Новый пароль',
						'add_role' => 'Добавлена роль: %1$s',
						'remove_role' => 'Удалена роль: %2$s',
						'_create' => 'Пользователь создан',
						'_delete' => 'Пользователь удален',
				],
				'master' => [
						'name_ru'  => 'Имя преподавателя (Ру): %2$s → %1$s',
						'name_en'  => 'Имя преподавателя (En): %2$s → %1$s',						
						'alias' 	 => 'Урл: %2$s → %1$s',
						'priority'     => 'Порядок: %2$s → %1$s',
						'status'     => 'Статус: %2$s → %1$s',						
						'summary_ru'  => 'Изменено краткое описание (Ру)',
						'summary_en'  => 'Изменено краткое описание (En)',
						'body_ru'  => 'Изменено полное описание (Ру)',
						'body_en'  => 'Изменено полное описание (En)',
						'education_ru'  => 'Изменено образование (Ру)',
						'education_en'  => 'Изменено образование (En)',
						'consultation_ru'  => 'Изменено консультации (Ру)',
						'consultation_en'  => 'Изменено консультации (En)',						
						'seo_title_ru' => 'seo_title (Ру): %2$s → %1$s',
						'seo_title_en' => 'seo_title (En): %2$s → %1$s',
						'seo_description_ru' => 'Изменен seo_description (Ру)',
						'seo_description_en' => 'Изменен seo_description (En)',
						'seo_keywords_ru' => 'Изменен seo_keywords (Ру)',
						'seo_keywords_en' => 'Изменен seo_keywords (En)',						
						'personal' => 'Персональные консультации: %2$s → %1$s',
						'group'  => 'Преподавание в группах: %2$s → %1$s',
						'image'  => 'Изменено фото: %2$s → %1$s',
						'add_review' => 'Добавлен отзыв № %1$s',
						'remove_review' => 'Удален отзыв № %2$s',
				],
				'master-prices' => [					
					'name_ru'  => 'Название (Ру): %2$s → %1$s',
					'name_en'  => 'Название (En): %2$s → %1$s',
					'price_desc_ru'  => 'Расшифровка (Ру): %2$s → %1$s',
					'price_desc_en'  => 'Расшифровка (En): %2$s → %1$s',
					'price' 	 => 'Цена: %2$s → %1$s',
					'priority'     => 'Порядок: %2$s → %1$s',
					'status'     => 'Статус: %2$s → %1$s', 
					'master_id'  => 'Специалист: %2$s → %1$s',
					'_create' => 'Создание',
					'_delete' => 'Уудаление',
				],
				'customer' => [
					'name' => 		'Имя клиента: %2$s → %1$s',
					'city' => 		'Город: %2$s → %1$s',
					'description' => 'Изменен текст "о себе"',
					'birthday' => 	'День рождения: %2$s → %1$s',
					'sex' => 		'Пол: %2$s → %1$s',
					'image' => 		'Фото: %2$s → %1$s',
				],
				'videoalbum' => [
						'title_ru' => 'Название (Ру): %2$s → %1$s',
						'title_en' => 'Название (En): %2$s → %1$s',
						'alias' => 'УРЛ: %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'priority'     => 'Порядок: %2$s → %1$s',
						'seo_title_ru' => 'seo_title (Ру): %2$s → %1$s',
						'seo_title_en' => 'seo_title (En): %2$s → %1$s',
						'seo_description_ru' => 'Изменен seo_description (Ру)',
						'seo_description_en' => 'Изменен seo_description (En)',
						'seo_keywords_ru' => 'Изменен seo_keywords (Ру)',
						'seo_keywords_en' => 'Изменен seo_keywords (En)',
						'views' => 'views: %2$s → %1$s',
						'author' => 'Автор: %2$s → %1$s',
						'created' => 'Дата: %2$s → %1$s',
						'_create' => 'Видеоальбом создан',
						'_delete' => 'Видеоальбом удален',
				],
				
				'video' => [
						'title_ru' => 'Название (Ру): %2$s → %1$s',
						'title_en' => 'Название (En): %2$s → %1$s',
						'alias' => 'УРЛ: %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'top' => 'Топ: %2$s → %1$s',
						'priority'     => 'Порядок: %2$s → %1$s',
						'body_ru' => 'Изменен Текст (Ру)',
						'body_en' => 'Изменен Текст (En)',
						'seo_title_ru' => 'seo_title (Ру): %2$s → %1$s',
						'seo_title_en' => 'seo_title (En): %2$s → %1$s',
						'seo_description_ru' => 'Изменен seo_description (Ру)',
						'seo_description_en' => 'Изменен seo_description (En)',
						'seo_keywords_ru' => 'Изменен seo_keywords (Ру)',
						'seo_keywords_en' => 'Изменен seo_keywords (En)',
						'views' => 'views: %2$s → %1$s',
						'author' => 'Автор: %2$s → %1$s',
						'created' => 'Дата: %2$s → %1$s',
						'_create' => 'Видео создано',
						'_delete' => 'Видео удалено',
				],
				
				'photoalbum' => [
						'title_ru' => 'Название (Ру): %2$s → %1$s',
						'title_en' => 'Название (En): %2$s → %1$s',
						'body_ru' => 'Изменен Текст (Ру)',
						'body_en' => 'Изменен Текст (En)',
						'status' => 'Статус: %2$s → %1$s',
						'seo_title_ru' => 'seo_title (Ру): %2$s → %1$s',
						'seo_title_en' => 'seo_title (En): %2$s → %1$s',
						'seo_description_ru' => 'Изменен seo_description (Ру)',
						'seo_description_en' => 'Изменен seo_description (En)',
						'seo_keywords_ru' => 'Изменен seo_keywords (Ру)',
						'seo_keywords_en' => 'Изменен seo_keywords (En)',
						'created' => 'Дата: %2$s → %1$s',
						'_create' => 'Фотоальбом создан',
						'_delete' => 'Фотоальбом удален',
				],
				
				'photo' => [
						'title_ru' => 'Название (Ру): %2$s → %1$s',
						'title_en' => 'Название (En): %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'image' => 'Изображение: %2$s → %1$s',
						'views' => 'views: %2$s → %1$s',
						'_create' => 'Фото создано',
						'_delete' => 'Фото удалено',
				],
				
				'review' => [
						'name_ru' => 'Имя (Ру): %2$s → %1$s',
						'name_en' => 'Имя (En): %2$s → %1$s',
						'date' => 'Дата: %2$s → %1$s',
						'body_ru' => 'Изменен текст (Ру)',
						'body_en' => 'Изменен текст (En)',
						'status' => 'Опубликовано: %2$s → %1$s',
						'home' => 'Показывать на главной странице: %2$s → %1$s',
						'social' => 'Ссылка в соцсети: %2$s → %1$s',
						'userpic' => 'Юзерпик: %2$s → %1$s',
						'_create' => 'Отзыв создан',
						'_delete' => 'Отзыв удален',
				],				
// 				'diplom' => [
// 						'title' => 'Название (Ру): %2$s → %1$s',
// 						'title' => 'Название (En): %2$s → %1$s',
// 						'status' => 'Статус: %2$s → %1$s',
// 						'image' => 'Изображение: %2$s → %1$s',
// 						'master_id' => 'Преподаватель: %2$s → %1$s',
// 						'_delete' => 'Дипломы удален'
// 				],				
				'banner' => [
					'title' => 'Внутреннее название: %2$s → %1$s',
					'body_ru' => 'Изменен Текст (Ру)',
					'body_en' => 'Изменен Текст (En)',
					'link' => 'Ссылка: %2$s → %1$s',
					'status' => 'Статус: %2$s → %1$s',
					'priority' => 'Приоритет: %2$s → %1$s',
					'image' => 'Изображение: %2$s → %1$s',
					'bg_color' => 'Цвет фона: %2$s → %1$s',
					'date_from' => 'Показывать насиная с: %2$s → %1$s',
					'date_to' => 'Заверщить показ: %2$s → %1$s',
					'countdown' => 'Показывать обратный отсчет времени: %2$s → %1$s',
					'_delete' => 'Баннер удален'
				],
				'order_consultation' => [
						'name' => 'Имя: %2$s → %1$s',
						'phone' => 'Телефон для связи: %2$s → %1$s',
						'skype' => 'Скайп: %2$s → %1$s',
						'user_id' => 'Клиент: %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',						
						'master_id' => 'Специалист: %2$s → %1$s',
						'tarif_id' => 'Тариф: %2$s → %1$s',
						'date' => 'Дата заявки: %2$s → %1$s',
						'meet_date' => 'Дата и время мероприятия: %2$s → %1$s',
						'message' => 'Изменено Сообщение клиента',
						'_create' => 'Заявка создана',
						'_delete' => 'Заявка удалена',						
				],

				'order_call' => [
						'name' => 'Имя: %2$s → %1$s',
						'phone' => 'Телефон для связи: %2$s → %1$s',
						'user_id' => 'Клиент: %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'message' => 'Изменено Сообщение клиента',
						'_create' => 'Заявка создана',
						'_delete' => 'Заявка удалена'
				],

				'order_orders' => [
					'customer_id' => 'Клиент: %2$s → %1$s',
					'event_id' => 'Мероприятие: %2$s → %1$s',
					'date' => 'Дата: %2$s → %1$s',
					'tarif_id' => 'Тариф: %2$s → %1$s',
					'status' => 'Статус: %2$s → %1$s',
					'price' => 'Цена: %2$s → %1$s',
					'payed' => 'Оплата: %2$s → %1$s',
					'discounts' => 'Скидки изменены',					
					'message' => 'Изменено Сообщение клиента',
					'add_shedule' => 	'добавлена  встреча  %1$s',
					'remove_shedule' => 'отменена 	встреча  %2$s',
					'_create' => 'Заявка создана',
					'_delete' => 'Заявка удалена'
				],
				'course' => [ 
						'title_ru' => 'Название (Ру): %2$s → %1$s',
						'title_en' => 'Название (En): %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'priority' => 'Приоритет: %2$s → %1$s',
						'image' => 'Изменено изображение',
						'summary_ru' => 'Краткое описание (Ру): %2$s → %1$s',
						'summary_en' => 'Краткое описание (En): %2$s → %1$s',
						'body_ru' => 'Описание (Ру): %2$s → %1$s',
						'body_en' => 'Описание (En): %2$s → %1$s',
						
						'seo_title_ru' => 'seo_title (Ру): %2$s → %1$s',
						'seo_title_en' => 'seo_title (En): %2$s → %1$s',
						'seo_description_ru' => 'Изменен seo_description (Ру)',
						'seo_description_en' => 'Изменен seo_description (En)',
						'seo_keywords_ru' => 'Изменен seo_keywords (Ру)',
						'seo_keywords_en' => 'Изменен seo_keywords (En)',
						
						'add_tag' => 'Добавлен тег %1$s',
						'remove_tag' => 'Удален тег %2$s',
						
						'shedule' => 'Изменено расписание',
						'_create' => 'Объект создан',
						'_delete' => 'Курс удален' 
				],
				
				'event' => [ 
						'course_id' => 'Курс: %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'type' => 'Периодичность мероприятия: %2$s → %1$s',
						'count' => 'Количество мест: %2$s → %1$s',
						
						'date_text_ru' => 'Дата текстом (Ру): %2$s → %1$s',
						'time_text_ru' => 'Время текстом (Ру): %2$s → %1$s',
						
						'date_text_en' => 'Дата текстом (En): %2$s → %1$s',
						'time_text_en' => 'Время текстом (En): %2$s → %1$s',
						
						'add_master' => 'Добавлен ведущий %1$s',
						'remove_master' => 'Удален ведущий %2$s',
						
						'add_tarif' => 'Добавлен тариф %1$s',
						'remove_tarif' => 'Удален тариф %2$s',						
						'expiration_date' => 'Дата завершения записи: %2$s → %1$s',
						'_create' => 'Объект создан',
						'_delete' => 'Мероприятие удалено' 
				],
				
				'tarifs' => [ 
						'title_ru' => 'Название (Ру): %2$s → %1$s',
						'title_en' => 'Название (En): %2$s → %1$s',
						'price_desc_ru'  => 'Расшифровка (Ру): %2$s → %1$s',
						'price_desc_en'  => 'Расшифровка (En): %2$s → %1$s',
						'course_id' => 'Курс: %2$s → %1$s',
						'status' => 'Статус: %2$s → %1$s',
						'priority' => 'Приоритет: %2$s → %1$s',
						'price' => 'Цена: %2$s → %1$s',
						'discounts' => 'Скидки: %2$s → %1$s',
						'subscription' => 'Кол-во встреч: %2$s → %1$s',
						'type' => 'Тип тарифа: %2$s → %1$s',
						'_create' => 'Объект создан',
						'_delete' => 'Тариф удален' 
				],
				'todo' => [
						'title' => 'Заголовок: %2$s → %1$s',
						'body' => 'Изменен Текст',
						'status' => 'Статус: %2$s → %1$s',
						'intensity' => 'Трудоемкость: %2$s → %1$s',
						'priority' => 'Приоритет: %2$s → %1$s',
						'user' => 'Cотрудник: %2$s → %1$s',						
						'till_date' => 'Дата: %2$s → %1$s',
						'_create' => 'Напоминание создано',
						'_delete' => 'Напоминание удалено',
				],
				
		]
];
