<?
use Common\ViewHelper\Assets;

/* @var $this Zend\View\Renderer\PhpRenderer */

if($this->identity()->isAdmin()){	
	$this->inlineScript()->appendFile('/assets/ckeditor/ckeditor.js', 'text/javascript', ['nominifi' => true])
		// ->appendFile('/assets/ckeditor/config.js', 'text/javascript', ['nominifi' => true])
		->appendFile('/site/js/admin.js', 'text/javascript', ['nominifi' => true]);
}
?>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<?= $this->headTitle($this->translate('Ольвия. Центр семейного консультирования'))->setSeparator(' - ')->setAutoEscape(false) ?>
	
	<?= $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>
	<?= $this
			->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.png'))
			// ->prependStylesheet('/assets/fancybox/jquery.fancybox.min.css')
			->prependStylesheet('/assets/fontello/css/animation.css')
			->prependStylesheet('/assets/fontello/css/fontello-embedded.css')
			->prependStylesheet('/site/css/_signe-form.css')
			->prependStylesheet('/site/css/_call-form.css')
			->prependStylesheet('/site/css/style.css')
			->prependStylesheet('/site/css/fonts.css')
			->prependStylesheet('/site/css/reset.css');            		
	;
	?>
	
	<?= $this->headScript()	?>
	
</head>