<?
use Common\ImageService;

/* @var $this Common\View */
$this->headTitle("Курсы");
$this->assets(['fancybox']);
$this->sidebar()->left('admin/courses/course/course-index.filter.phtml', $this->vars());
?>
<ul class="breadcrumb">
	<li><a href="<?= $this->url('private') ?>">Главная</a></li>	
</ul>
<h1 class="page-header">Список курсов <small><?= $this->counts['count'] ?></small></h1>

<table class="item-list" data-deletion-confirm="Вы уверены, что хотите удалить этот объект?">
	<thead>
		<tr>
			<th style="width: 60px" class="tc">№</th>
			<th></th>
			<th>Название</th>			
			<th class="tc">Тарифы</th>
			<th class="tc">Мероприятия</th>
			<th class="tc">Приоритет</th>			
			<th></th>
		</tr>
	</thead>
	<?foreach ($this->items as $item) {?>
	<tr data-href="<?=$this->url('private/course-edit', ['id' => $item['id']])?>">
		<td class="tc"><?= $item['id']?></td>
		<td class="image">
			<a href="<?= $this->image( $item['image']) ?>" data-fancybox="gallery" title="<?= htmlspecialchars($item['title']) ?>">
				<img src="<?= $this->image( $item['image'], ImageService::SIZE_ADMIN_LIST_THUMB ) ?>" />
			</a>
		</td>
		<td><?= $item['title'] ?></td>
		<td class="tc"><?= $item['tarif_count'] ?: '' ?></td>
		<td class="tc"><?= $item['event_count'] ?: '' ?></td>		
		<td class="tc"><?= $item['priority'] ?></td>
		<td class="options">
			 <a href="<?= $this->url('private/course-status', ['id' => $item['id']]) ?>" class="item-status">
				<i class="fa fa-check <?= $item['status'] ? 'active': '' ?>"></i></a>
				<a href="<?= $this->url('private/course-delete', ['id' => $item['id']]) ?>" class="fa fa-trash item-delete"></a>			
		</td>
	</tr>
	<?}?>
</table>	

<?= $this->html()->pages($this->page, $this->pageCount) ?>
