<?
use Common\ViewHelper\Assets;

/* @var $this Common\View */
/* @var $form Admin\Forms\Content\DivisionForm */
/* @var $item array */
$item = $this->item;

$this->sidebar()->left('admin/courses/course/course-edit.left.phtml', $this->vars());
$this->sidebar()->right('admin/courses/course/course-edit.right.phtml', $this->vars());
$this->assets([Assets::CKEDITOR, 'image-upload', 'tag-select']);
?>
<ul class="breadcrumb">
	<li><a href="<?= $this->url('private') ?>">Главная</a></li>	
	<li><a href="<?= $this->url('private/course-index') ?>">Список курсов</a></li>
</ul>
<h1 class="page-header"><?if ($this->isNew) {
	echo "Новый курс";
	$this->headTitle("Новый курс");
} else {
	echo $this->item['title'];
	$this->headTitle($item['title'] . " №" . $this->id);
}?>
</h1>

<?= $form->start() ?>

<div class="minimizable">
	<table class="form-wrapper-table">
		<tr>
			<td class="left-cell common-group">
				<h2>Общая информация <a href="javascript:;" class="minimize-link"></a></h2>
					<?= $form('title') ?>
					<?= $form('alias') ?>
					<?= $form('status') ?>
				
					<?= $form('priority') ?>
				
					<?= $form('image') ?>
				
					<?= $form('summary') ?>
	
			</td>
			<td class="right-cell seo-group">
				<h2>SEO<a href="javascript:;" class="minimize-link"></a></h2>
					<?= $form('seo_title') ?>
					<?= $form('seo_description') ?>
					<?= $form('seo_keywords') ?>
				<h2>Теги</h2>			
					<?= $form('tags')?>
			</td>
		</tr>
		
	</table>
</div>

<div class="body-group minimizable">	
	<h2>Описание курса<a href="javascript:;" class="minimize-link"></a></h2>
	<?= $form('body') ?>
</div>


<?= $form('*') ?>
<?= $form->end();?>