<?
/* @var $this Common\View */
$route = $this->routeName();
?>

<nav class="user-tabs">
	<ul>
		<li><? if($route == 'customer-calendar') { 
		?><span>Мои мероприятия</span><? 
		} else { 
		?><a href="<?= $this->url('customer-calendar') ?>">Мои мероприятия</a><? 
		} ?></li>
		<li>
		
		<? if($route == 'customer-history') { 
		?><span>Прошедшие мероприятия</span><? 
		} else { 
		?><a href="<?= $this->url('customer-history') ?>">Прошедшие мероприятия</a><? 
		} ?></li>

		<li>		
		<?  if($route == 'customer-cabinet') { 
		?><span>Личная информация</span><? 
		} else { 
		?><a href="<?= $this->url('customer-cabinet') ?>">Личная информация</a><? 
		} ?></li>
	</ul>
</nav><?

