<?
use Application\Model\UserDb;
$this->popup('callme');
$this->popupSigne();
/* @var $this Common\View */
?>
<header>
	<table class="lay-header">
		
		<tr class="line-1">
			<td>
				<a href="/">
					<img src="/mobile/img/logo.png" alt="Ольвия. Центр семейного консультирования" class="logo" />
				</a>
			</td>
			<td>		
				<a href="/"> 
					<span class="slogan-1">ОЛЬВИЯ</span> 					
					<span class="slogan-2">центр семейного консультирования </span>	
				</a>
			</td>
			<td>
				<nav class="main-menu">
					<?= $this->partial('/parts/main-menu.phtml') ?>
				</nav>	
				<a href="javascript:;" class="menu-button icon-menu">					
				</a>
			</td>
			
		</tr>
	</table>
</header>
<section class="header-line-2 purple">
	<p>	
		<a href="/contacts.php" class="address"><i class="icon-location"></i><nobr>м. Чеховская,</nobr> <nobr>м. Пушкинская,</nobr> <nobr>ул. Малая Дмитровка, 18а</nobr></a>
	</p>
	<p>
		<a href="tel:+74952266880" class="phone"><i class="icon-phone"></i><span><span class="code">7 495</span> 22-66-880</span></a>
		<a href="tel:+74952266876" class="phone"><i class="icon-phone"></i><span><span class="code">7 495</span> 22-66-876</span></a>
	</p>				
</section>
