<?
/* @var $this Common\View */
$this->headLink()->appendStylesheet("/site/css/_review-form.css");
$this->inlineScript()->appendFile("/site/js/_review-form.js");

?>

<div class="twm-popup" id="reviewPopup" >
   	<form action="/" method="post" class="form">
   		<h3>Оставить отзыв</h3>

   		<? if (empty($reviewSubject)){ ?> 
		<p class="error-msg">Заполните все поля</p>
		
		<div class="field">
			<label class="required">Ваше имя</label>
			<input type="text" name="name"/>
		</div>
		
		<div class="field">
			<label>Телефон для связи с Вами</label>
			<input type="text" name="phone" style="font-family: Consolas,Monaco,Lucida Console,monospace"/>
		</div>
		<? } ?>
		
		<div class="field">
			<label>Ссылка на страницу VF или FB</label>
			<input type="text" name="sozial" />
		</div>
		
		<div class="field">
			<label class="required">Ваш отзыв <?= $reviewSubject ?></label>
			<textarea name="message" ></textarea>
		</div>
		<div class="buttons">
			<a href="javascript:;" class="button light twm-close" >Отмена</a>
			<button type="submit" class="button purple" >Отправить</button>	
		</div>
	</form>
	<div class="done">
		<h3>Оставить отзыв</h3>
		<p>Спасибо за Ваш отзыв.<br/>Скоро он будет размещен на сайте</p>
		<div class="buttons">
			
			<a href="javascript:;" class="button purple twm-close" >OK</a>
		</div>
	</div>
</div>