<?
/* @var $this Common\View */

$type =  $this->type;
$meetDate = $this->meet_date;
$tarif = 	$this->tarif;
$masters = 	$this->masters;

?>

<div class="white-bg shedule-block">
	
	<div class="date-wrp">
		<p class="date-big"><?= $this->html()->date($meetDate, 'd')?></p>
		<p class="date"><?= $this->html()->date($meetDate, 'M')?></p>
		<p class="date"><?= $this->html()->date($meetDate, ' l')?></p>
	</div>
	
	<div class="text-wrp">
		<h3><?= $this->event['title'] ?></h3>
		
		<? if(!empty($this->masters)) {?>
		<p class="info">Ведущий: 
			<?= implode(', ', array_map(function($master){
			return '<a class="" href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
			}, $this->masters)); ?>
		</p>
		<? } ?>
				
	</div>
	
	<div class="clr"></div>
	<p class="status">
		<? if(!empty($this->course['alias'])) { ?>
		<a href="#reviewPopup" class="button twm-popup-link" data-subject="course-<?= $this->course['alias']?>">Оставить отзыв</a>
		<? } ?>
	</p>
	
</div>