<?
/* @var $this Common\View */
$this->headTitle("Мое распиание");
$this->headLink()->appendStylesheet("/mobile/css/user.css");

?>

<a href="/" class="breadcrumb-bar">Главная</a>

<h1>Мой календарь</h1>

<?= $this->userFlowFlash() ?>

<? if($this->total != 0 ) {?>
	<div class="white-bg payment-block">
		<h2>Оплата мероприятий</h2>
		<p><a href="/user-courses.php?action=payment" class="button pink">К оплате: <?= number_format($this->total, 0, '.', ' ')?> р.</a></p>
		<? if($this->totalDiscount != 0 ){ ?> 
		<p>Экономия при оплате online: <span class="value nobr"><?= number_format($this->totalDiscount, 0, '.', ' ')?></span>р</p>
		<? } ?>						
	</div>
<? } ?>
	
<? foreach ($this->orders as $order){ 
	if($order['type'] == 'consult'){
	// echo $this->partial('customer-calendar.consult.phtml', $order);
	} else if ($order['type'] == 'order' || $order['type'] == 'preorder') {
		echo $this->partial('customer-calendar.order.phtml', $order);
	}
} ?>
		
<? if($this->total != 0 ) {?>
	<div class="white-bg payment-block">
		<h2>Оплата мероприятий</h2>
		<p><a href="/user-courses.php?action=payment" class="button pink">К оплате: <?= number_format($this->total, 0, '.', ' ')?> р.</a></p>
		<? if($this->totalDiscount != 0 ){ ?> 
		<p>Экономия при оплате online: <span class="value nobr"><?= number_format($this->totalDiscount, 0, '.', ' ')?></span>р</p>
		<? } ?>						
	</div>
<? } ?>		
		

<div class="twm-popup" id="removeCoursePopup" >	
	<form action="/" method="post" class="form">
		<p>Вы уверены, что хотите отменить свою запись на мероприятие?</p>			
		<div class="buttons">
			<a href="javascript:;" class="button purple twm-close" >Нет</a>		
			<a href="javascript:;" class="button purple" >Да</a>
		</div>		
	</form>
</div>