<?
/* @var $this Common\View */
$this->headTitle("Мое распиание");
$this->headLink()->appendStylesheet("/mobile/css/user.css");
$this->popup('review');

?>

<a href="/" class="breadcrumb-bar">Главная</a>

<h1>Прошедшие мероприятия</h1>

<nav class="month-pager">
<?// TODO ПАгинатор на странице истории у клиента 
// = $this->monthPaginator($this->currentDate, ['end' => time()], 3); ?>	
</nav>	

<? foreach ($this->orders as $item){ 
	if($item['type'] == 'consult'){
		echo $this->partial('/application/customer/calendar/customer-history.consult.phtml', $item);
	} else {
		echo $this->partial('/application/customer/calendar/customer-history.order.phtml', $item);
	}
} ?>
<nav class="month-pager">
<?// = $this->monthPaginator($this->currentDate, ['end' => time()], 3); ?>
</nav>