<?php
use Admin\Model\Courses\EventDb;
use Admin\Model\Orders\OrdersDb;

/* @var $this Common\View */
	$type =  $this->type;
	$meetDate = $this->meet_date;
	$order = 	$this->order;
	$shedule = 	$this->shedule;
	$event = 	$this->event;
	$tarif = 	$this->tarif;
	$masters = 	$this->masters;
?>
<div class="white-bg shedule-block">
	<div class="date-wrp">
		<? if($type == 'preorder'){ ?>
			<p class="date"><?= $event['date_text']?></p>
			<p class="date">Предзаказ</p>					
		<? } else { ?>
			<p class="date-big"><?= $this->html()->date($meetDate, 'd')?></p>
			<p class="date"><?= $this->html()->date($meetDate, 'M')?></p>
			<p class="date"><?= $this->html()->date($meetDate, ' l')?></p>
		<? }?>
		
	
		<? if(!empty($event['time_text'])){ ?>
		<p class="time-till-wrp">		
			<? if(!empty($event['time_text_from'])){ ?>
			<span class="from"><?= $event['time_text_from'] ?></span>
			<? if(!empty($event['time_text_till'])){ ?>
			<span class="till"><?= $event['time_text_till'] ?></span>
			<? } ?>
			<? } else { ?> 
			<span class="till"><?= $event['time_text_duration'] ?></span>
			<? } ?>		
		</p>
		<? }?>	
	</div>
	<div class="text-wrp" >		
		<h3><?= $event['title'] ?></h3>		
		<? if(!empty($masters)) {?>
		<p class="info">Ведущий: 
			<?= implode(', ', array_map(function($master){
			return '<a class="" href="'. $this->url('master-view', ['alias' => $master['alias']]) .'">'. $master['name'] .'</a>';
			}, $masters)); ?>
		</p>
		<? } ?>
			
		<? if($event['type'] != EventDb::TYPE_ANNOUNCE){ ?>
		<p class="info">Адрес: 
			<a href="javascrpt:;"><i class="icon-location"></i> м. Пушкинская, ул. Малая Дмитровка, 18а </a>			
		</p>
		<? } ?>
		<p class="info">Тариф:
			<?= $tarif['title'] ?>
			<? 
			if ($order['actual_price'] == 0){ ?>
				<span class="free">бесплатно</span>			
			<? } else if (empty($order['payed'])){ ?>
				<label class="checkbox">
					<span class="price"><?= number_format($order['actual_price'], 0, '.', ' ')?> р.</span>
					<? if($order['actual_price'] < $order['price'] && $order['price']!=0){ ?> 
					<span class="price-old"><?= number_format($order['price'], 0, '.', ' ')?> р.</span>
					<? } ?>
				</label>
			<? } ?>
		</p>
	</div>
	<div class="clr"></div>
	<p class="status">		
		
		<? if($order['actual_price'] != 0){
			if (empty($order['payed'])){ ?>
			<label class="checkbox">
				<input type="checkbox" name="payment" checked="checked" data-value="<? $order['actual_price'] ?>" />
				<span>Оплатить</span>	
			</label>
			<? } else { ?>
			<label class="payed"><i class="icon-check-1"></i> оплачено <?= number_format($order['payed'], 0, '.', ' ')?> р.</span></label>
			<? } ?>
		<? } ?>
		
		<? if (empty($order['payed']) && ($order['status'] == OrdersDb::STATUS_PREORDER || $order['status'] == OrdersDb::STATUS_NEW)){ ?>
			<a href="#removeCoursePopup" class="twm-popup-link cancel-link">отменить</a>			
		<? } ?>
	
	</p>
		
</div>