<?
/* @var $this Common\View */
?>
<form class="form v-form">
	
	<div class="field">
		<input type="text" name="f[query]" value="<?= $this->filter['query'] ?>" placeholder="Поиск..." />
	</div>
		
	<div class="button-group">
		<a href="<?= $this->url(null, ['p' => 1, 'f' => null]) ?>" type="submit" class="button reset">Сбросить</a>
		<button type="submit" class="button">Искать</button>
	</div>
	
</form>
<div>
	<a href="<?= $this->url('private/review-edit', ['id' => 'new']) ?>" class="button create-item-link">Новый отзыв</a>
</div>