<?
/* @var $this Common\View */
?>
<form class="form v-form">
	<div class="field">
		<input type="text" name="query" placeholder="Поиск..." />
	</div>
	<div class="field">
		<label>Группа пользователей</label> <select>
			<option value="admin">Все пользователи</option>
			<option value="admin">Администраторы</option>
			<option value="master">Специалисты</option>
			<option value="student">Ученики</option>
		</select>
	</div>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p>
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
<!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellat tempora rem eius quo vero labore harum. Quasi ad ullam quaerat suscipit nisi molestiae illo voluptatibus dolorem fugiat repudiandae doloremque consectetur?</p> -->
</form>