<?
use Common\ImageService;

/* @var $this Common\View */
$item = $this->item;
?>
<tr data-href="<?=$this->url('private/photo-edit', ['id' => $item['id']])?>">
	<td class="tc"><?= $item['id']?></td>
	<td class="image">
		<a href="<?= $this->image( $item['image']) ?>" data-fancybox="gallery" title="<?= htmlspecialchars($item['title']) ?>">
			<img src="<?= $this->image( $item['image'], ImageService::SIZE_ADMIN_LIST_THUMB ) ?>" />
		</a>
	</td>
	<td><?= $item['title'] ?></td>
	<td>
		<? if (!empty($item['photoalbum_id'])) { ?>
		<a href="<?= $this->url('private/photoalbum-edit', ['id' => $item['photoalbum_id']]) ?>">
		<?= $item['photoalbum_name'] ?>
		</a>
		<? } ?>
	</td>
	<td class="tr">
		<?= $this->html()->date($item['created']) ?>
	</td>
	<td class="tc"><?= $item['views'] ?></td>
	<td class="tc"><?= $item['priority'] ?></td>
	<td class="options">
		<a href="<?= $this->url('private/photo-status', ['id' => $item['id']]) ?>" class="item-status">
			<i class="fa fa-check <?= $item['status'] ? 'active': '' ?>"></i></a>
		<a href="<?= $this->url('private/photo-delete', ['id' => $item['id']]) ?>" class="fa fa-trash item-delete"></a>			
	</td>
</tr>