<?
/* @var $this Common\View */
$this->headTitle($this->division['seo_title']);
if(!empty($this->article['seo_keywords'])){
	$this->headMeta($this->division['seo_keywords'], "keywords");
}
if(!empty($this->article['seo_description'])){
	$this->headMeta($this->division['seo_description'], "description");
}

$this->inlineScript()->appendFile("/mobile/js/article.js");
$this->headLink()->appendStylesheet('/mobile/css/content-index.css');
?>

<a href="<?= $this->url('content-index') ?>" class="breadcrumb-bar">Все статьи</a>

<h1>Статьи: <?= $this->division['title'] ?></h1>

<div class="block-wrp">
	<img src="<?= $this->image($this->division['image'],  400, 200) ?>">
	<ul>
		<? foreach ($articles as $article){ ?>
		<li>
			<a href="<?= $this->url('content-article', ['alias' => $article['alias']]) ?>">
			<?= $this->html()->hdate($article['created']) ?>
			<?= $article['title'] ?>
			<div>
				<?= $article['intro'] ?>
			</div>	
			</a>			
			</li>
		<? } ?> 
	</ul>
</div>