<?
/* @var $this Common\View */
$this->headTitle('Самое интересное в разделе статьи');
$this->inlineScript()->appendFile("/site/js/article.js");
$this->headLink()->appendStylesheet('/site/css/content-index.css');
?>

<ul class="breadcrumb">
	<li><a href="/">Главная</a></li>
	<li>Статьи</li>
</ul>

<h1>Самое интересное в разделе статьи</h1>

<div class="block-wrp">
	<? foreach ($this->divisions as $division){ ?>
	<div class="block white-bg">
		<a href="<?= $this->url('content-division', ['alias' => $division['alias']]) ?>">
			<img src="<?= $this->image($division['image'], 367, 229) ?>" alt="<?= htmlentities($division['title']) ?>">
			<h2><?= $division['title'] ?></h2>
		</a>
		
		<ul>
			<? foreach ($division['items'] as $article){ ?>
			<li><a href="<?= $this->url('content-article', ['alias' => $article['alias']]) ?>"><?= $article['title'] ?> </a></li>
			<? } ?> 
			<? if ($division['article_count'] > count($division['items'])) { ?>
			<li><a href="<?= $this->url('content-division', ['alias' => $division['alias']]) ?>" class="view-more">Еще статьи по теме (<?= $division['article_count'] ?>)...</a></li>
			<? } ?>
		</ul>		
	</div>
	<? } ?>
</div>