<?
/* @var $this Common\View */
?>
<h2>Аккаунт пользователя</h2>
<div class="scrollspy" style="min-height: 80px;"></div>

<?= $this->partial('admin/users/users-edit.profiles-menu.phtml', $this->vars()) ?> 

<? if(!$this->isNew) { ?>
<h2>Статистика</h2>
<div class="statistics">
	<?= $this->partial('admin/parts/stat.phtml', ['stat' => $this->stat]); ?>	
	<div>
		<label>Залогинился:</label> <span><?= $this->html()->hdate($this->stat['logged']) ?></span>
	</div>
	<div>
		<label>Был на сайте:</label> <span><?= $this->html()->hdate($this->stat['accessed']) ?></span>
	</div>
</div>
<? }