<?
/* @var $this Common\View */
?>

<section class="services">
	<div class="lay-wrapper-inner">
		<h2 class="like-h1">Наш профиль</h2>
		<div class="block-wrp">
			<div class="block">
				<h3>Семья и отношения</h3>
				<img src="/site/img/services-1.jpg" alt="Семья и отношения" />
				<ul>
					<li><a href="/article.php">Причины депрессии</a></li>
					<li><a href="/article.php">Причины страха и его последствия</a></li>
					<li><a href="/article.php">Психосоматика. Скрытые причины заболеваний</a></li>
					<li><a href="/article.php">Причины гинекологических заболеваний</a></li>
					<li><a href="/article.php">Причины мужских заболеваний</a></li>
					<li><a href="/article.php">Причины желания суицида</a></li>
					<li><a href="/article.php">Как добиться целей, исполнение желаний</a></li>
					<li><a href="/article.php">Плохое самочувствие</a></li>
					<li><a href="/article.php">Женская гимнастика, развитие интимных мышц</a></li>
					<li><a href="/article.php">Развитие интуиции, чувств</a></li>
					<li><a href="/article.php">Снятие зажимов, комплексов, блоков</a></li>
					<li><a href="/article.php">Выяснение причин недомоганий, слабости</a></li>
				</ul>
			</div>
			<div class="block">
				<h3>Тело и здоровье</h3>
				<img src="/site/img/services-2.jpg" alt="Тело и здоровье" />
				<ul>
					<li><a href="/article.php">Анализ совместимости партнёров</a></li>
					<li><a href="/article.php">Почему не получается выйти замуж</a></li>
					<li><a href="/article.php">Решение конфликтов в семье</a></li>
					<li><a href="/article.php">Почему супруг хочет развестись</a></li>
					<li><a href="/article.php">Причины измен</a></li>
					<li><a href="/article.php">Возможные причины бесплодия</a></li>
					<li><a href="/article.php">Последствия абортов и выкидышей</a></li>
					<li><a href="/article.php">Почему подходят не те мужчины</a></li>
					<li><a href="/article.php">Секс и брак</a></li>
					<li><a href="/article.php">Любовный треугольник</a></li>
					<li><a href="/article.php">Как понять своего ребёнка</a></li>
					<li><a href="/article.php">Конфликты между супругами, родителями и детьми</a></li>
				</ul>
			</div>
			<div class="block last">
				<h3>Бизнес и карьера</h3>
				<img src="/site/img/services-3.jpg" alt="Бизнес и карьера" />
				<ul>
					<li><a href="/article.php">Оценка персонала</a></li>
					<li><a href="/article.php">Просмотр возможных путей развития ситуации</a></li>
					<li><a href="/article.php">Принятие решения при ограниченной информации</a></li>
					<li><a href="/article.php">Почему плохая атмосфера в коллективе, мотивация</a></li>
					<li><a href="/article.php">Кого стоит принять на должность руководителя</a></li>
					<li><a href="/article.php">Как отреагируют покупатели на новую услугу, товар</a></li>
					<li><a href="/article.php">Как понять собеседника, невербальная коммуникация</a></li>
					<li><a href="/article.php">Как правильно общаться с клиентами</a></li>
					<li><a href="/article.php">Чего не хватает компании для развития</a></li>
					<li><a href="/article.php">Какая связь между личной терапией топ менеджеров и успехами компании</a></li>
					<li><a href="/article.php">Почему высокая текучесть кадров</a></li>
					<li><a href="/article.php">NLP в бизнесе</a></li>
				</ul>
			</div>
		</div>
		<div class="button-group">
			<a href="/shedule-list.php" class="button light">Расписание мероприятий</a> <a href="#signPopup" class="button purple twm-popup-link">Записатся на консультацию</a>
		</div>
	</div>
</section>