<?
use Common\ImageService;
/* @var $this Common\View */
$banners = $this->banners;
if (empty($banners)){return ;}
?>

<section class="lay-banner">	
	<ul class="banner">
		<? foreach ($banners as $banner){ ?>
		<li style="background: <?= $banner['bg_color'] ?> url(<?= $this->image($banner['image'], ImageService::SIZE_BANNER) ?>) center center no-repeat"<? 
			?> class="<?= $banner['alias'] ?>"<?		
			?> data-href="<?= $banner['link'] ?>">
			<? if(!empty($banner['body'])){ ?>
			<div class="lay-wrapper-inner">
				<?= $banner['body'] ?>
			</div>
			<? } ?>
		</li>	
		<? } ?>		
	</ul>	
</section>