<?
/* @var $this Common\View */
/* @var $this Zend\View\Renderer\PhpRenderer */
$this->headTitle("Специалисты");
$this->sidebar()->left('admin/users/master/master-index.filter.phtml', $this->vars());

?><h1 class="page-header">Специалисты <small><?= $this->counts['count'] ?></small></h1>

<table class="item-list">
	<thead>
		<tr>
			<th style="width: 60px" class="tc">№</th>
			<th>Имя</th>
			<th>Аккаунт</th>			
			<th></th>				
		</tr>
	</thead>
	<?foreach ($this->items as $item) {?>
	<tr data-href="<?=$this->url('private/customer-edit', ['id' => $item['id']])?>">
		<td class="tc"><?= $item['id']?></td>
		<td><?= $item['name']?></td>
		<td><?= $item['displayname']?></td>
		<td class="options">
			<a href="<?= $this->url('private/master-status', ['id' => $item['id']]) ?>" class="item-status">
				<i class="fa fa-check <?= $item['active'] ? 'active': '' ?>"></i></a>
		</td>
	</tr>
	<?}?>
</table>
<?= $this->html()->pages($this->page, $this->pageCount)?>
